FROM rust:1-bookworm AS builder
WORKDIR /app
COPY backend /app/backend
RUN cd /app/backend && cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/backend/target/release/speedo-backend /usr/local/bin/

ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8080

EXPOSE 8080
CMD ["speedo-backend"]
